openai_creds:
  api_key: YOUR_OPENAI_API_KEY

anthropic_creds:
  api_key: YOUR_ANTHROPIC_API_KEY

gemini_creds:
  api_key: YOUR_GEMINI_API_KEY

deepseek_creds:
  api_key: YOUR_DEEPSEEK_API_KEY

xai_creds:
  api_key: YOUR_XAI_API_KEY

